# ==========================================================
# Algorithm
# ==========================================================

algorithm:
  name: "ppo"

  shared_policy: False
  centralized_critic: False #Independent PPO → centralized_critic=False; MAPPO / CTDE → centralized_critic=True
  recurrent: False

# ==========================================================
# Training
# ==========================================================

training:
  total_timesteps: 1000000

  gamma: 0.99
  gae_lambda: 0.95

  learning_rate: 0.0001

  batch_size: 4096
  mini_batch_size: 256

  ppo_epochs: 10
  clip_range: 0.2

  entropy_coef: 0.01
  value_loss_coef: 0.5
  max_grad_norm: 0.5

  freeze_one_agent: False
  # For PSRO oracle training, no affected by freeze_one_agent since we manually control which agent to train in PSRO loop
  # For example, boxing env, if freeze_one_agent=True, then PPO will only update agent_0's policy, treating agent_1 as part 
  # of the environment. This can help stabilize training when the opponent is also learning. 
  # If freeze_one_agent=False, then PPO will update both agents' policies simultaneously, 
  #which can lead to non-stationarity and instability in training.

# ==========================================================
# Enemy
# ==========================================================
# works with freeze_one_agent, you can load an enemy for training the learner model.
existing_enemy:
  enabled: False # disable if run PSRO, since it have seperated trigger.
  enemy_dir: ./checkpoints/ppo_enemy/enemy_agent.pt # default for PPO class

# ==========================================================
# Evaluation
# ==========================================================

evaluation:
  enabled: False # disable if run PSRO.
  eval_interval: 50000
  eval_episodes: 5

# ==========================================================
# Logging
# ==========================================================

logging:
  enabled: False # disable if run PSRO.
  log_type: "independent" # "mean" or "max" or "independent"
  log_interval: 4096
  enable_saving: False # set "False" for PSRO, since PSRO has its own population saving mechanism.
  save_model_interval: 250000

# ==========================================================
# Device
# ==========================================================

device:
  use_cuda: true
  gpu_id: 0

# ==========================================================
# Model
# ==========================================================

model:
  actor_hidden_sizes: [256, 256]
  critic_hidden_sizes: [256, 256]
  activation: "relu"