# ==========================================================
# Algorithm
# ==========================================================

algorithm:
  name: psro

  # Base RL oracle learner
  oracle_algorithm: ppo
  # For PPO oracle: it only works with independent policies (shared_policy=False)

  shared_policy: False
  centralized_critic: False

# ==========================================================
# Device
# ==========================================================

device:
  use_cuda: true
  gpu_id: 0

# ==========================================================
# PSRO
# ==========================================================

psro:

  # Number of PSRO iterations
  iterations: 20

  # for each oracle training phase
  oracle_training_steps: 40960

  # Population size limit
  max_population_size: 3

  # Meta strategy solver
  meta_solver: fictitious_play

  # uniform / latest / meta_strategy
  response_sampling: meta_strategy

  # Add new oracle only if improvement
  add_only_if_improved: true

  # Payoff discounting
  payoff_gamma: 1.0

  # Round-robin evaluation (Haven't implemented yet, so set to False)
  round_robin: False 

# ==========================================================
# Self-Play
# ==========================================================

self_play:

  # Probability of sampling latest policy
  latest_policy_prob: 0.3

  # Probability of random population sampling
  population_sampling_prob: 0.7


# ==========================================================
# PSRO logging
# ==========================================================
psro_logging:

  enabled: True

  # per PSRO iteration
  log_interval: 1 

  save_population_interval: 1

# ==========================================================
# PSRO evaluation
# ==========================================================
psro_evaluation:
  # Save each new oracle
  enabled: True

  eval_episodes: 5