# ==========================================================
# Algorithm
# ==========================================================

algorithm:
  name: psro

  # Base RL oracle learner
  oracle_algorithm: ppo
  # For PPO oracle: it only works with independent policies (shared_policy=False)

  shared_policy: False
  centralized_critic: False

# ==========================================================
# Device
# ==========================================================

device:
  use_cuda: true
  gpu_id: 0

# ==========================================================
# PSRO
# ==========================================================

psro:

  # Number of PSRO iterations
  iterations: 25

  # for each oracle training phase
  oracle_training_steps: 4097

  # Population size limit
  max_population_size: 1

  # Meta strategy solver: "fictitious_play" or "nash"
  meta_solver: nash

  # uniform / latest / meta_strategy
  response_sampling: meta_strategy

  # Add new oracle only if improvement
  add_only_if_improved: true

  # Payoff discounting
  payoff_gamma: 1.0

  # Round-robin evaluation (Haven't implemented yet, so set to False)
  round_robin: False 

# ==========================================================
# Enemy
# ==========================================================
# Only for evaluation, aligning with other baselines like PPO.
psro_existing_enemy:

  enabled: False

  enemy_dir: ./checkpoints/ppo_enemy/enemy_agent.pt # default for ppo oracle


# ==========================================================
# PSRO logging
# ==========================================================
psro_logging:

  enabled: True

  # per PSRO iteration
  log_interval: 1 

  save_population_interval: 5

# ==========================================================
# PSRO evaluation
# ==========================================================
psro_evaluation:
  # Save each new oracle
  enabled: True

  eval_episodes: 5