# Note: QMIX is only defined for discrete action spaces
# For continuous spaces, argmax(Q) and Q-value vectors are not meaningful

# ==========================================================
# Algorithm
# ==========================================================

algorithm:
  name: "qmix"

  recurrent: true

# ==========================================================
# QMIX Settings
# ==========================================================

mixer:
  enabled: true
  type: "qmix"

  mixing_hidden_dim: 32
  hypernet_hidden_dim: 64

# ==========================================================
# Agent Network
# ==========================================================

model:
  agent_hidden_size: 128
  rnn_hidden_size: 64
  activation: "relu"

# ==========================================================
# Replay Buffer
# ==========================================================

buffer:
  type: "episode"

  capacity: 1024

  burn_in_steps: 0

# ==========================================================
# Training
# ==========================================================

training:
  total_timesteps: 1000000

  gamma: 0.99

  learning_rate: 0.0005

  target_update_interval: 200

  double_q: true

  grad_norm_clip: 10.0

  train_interval: 1

  learner_updates_per_step: 1

  train_epochs: 10  # For PPO-style multiple epochs per update

  mini_batch_size: 128

  freeze_one_agent: True
  # For PSRO oracle training, no affected by freeze_one_agent since we manually control which agent to train in PSRO loop
  # For example, boxing env, if freeze_one_agent=True, then PPO will only update agent_0's policy, treating agent_1 as part 
  # of the environment. This can help stabilize training when the opponent is also learning. 
  # If freeze_one_agent=False, then PPO will update both agents' policies simultaneously, 
  #which can lead to non-stationarity and instability in training.

# ==========================================================
# Enemy
# ==========================================================
# works with freeze_one_agent, you can load an enemy for training the learner model.
existing_enemy:
  enabled: False # disable if run PSRO, since it have seperated trigger.
  enemy_dir: ./checkpoints/qmix_enemy/enemy_agent.pt # default for QMIX class

# ==========================================================
# Exploration
# ==========================================================

exploration:
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay_steps: 500000

# ==========================================================
# Evaluation
# ==========================================================

evaluation:
  enabled: False # disable if run PSRO, since it have seperated trigger.

  eval_interval: 10000
  eval_episodes: 5

  deterministic: true

# ==========================================================
# Logging
# ==========================================================

logging:
  enabled: False # disable if run PSRO, since it have seperated trigger.
  log_type: "independent"  # "mean" or "max" or "independent"
  log_interval: 4096
  enable_saving: True # set "False" for PSRO, since PSRO has its own population saving mechanism.
  save_model_interval: 250000

# ==========================================================
# Device
# ==========================================================

device:
  use_cuda: true
  gpu_id: 0